.\" Process this file with
.\" groff -man -Tascii freedroidRPG.6
.\" 
.\" Or even better, use
.\" 
.\"    man -l freedroidRPG.6 
.\" 
.\" to test the local copy of the man page source file.
.\" 
.TH FREEDROID 6 "MARCH 2003" Linux "User Manuals"
.SH NAME
freedroidRPG \- a graphical single player role playing game featuring Tux the Linux mascot
.\" 
.\" 
.\" 
.\" 
.\" 
.SH SYNOPSIS
.B freedroidRPG [ options
.B ]
.SH DESCRIPTION
.B FreedroidRPG
is a graphical single player role playing game inspired by games like Diablo and Gothic.

In a far-future world, almost all services and jobs were done by robots and droids,
most especially the more dangerous ones like police or military services.
The company providing the operating systems for these bots 'MegaSoft' used their
closed source operating system monopoly and a back door within it's operation system
to enslave humanity all over the galaxy.

But this is not the main problem.  Some 20 years after the MS has taken control of the 
universe, suddenly a very strange thing happened.  The bots suddenly rebelled against 
the MS and didn't respond to the commands of their former superiors at the MS any more.
Mankind was under attack by it's bots and had to flee to various secret underground
caverns on remote planets of the universe and cannot return any more.

This is where the game begins.  The Tux awakens from several years of stasis that the MS
has put him into and now returns to save the world from the horrible bots.
.\" 
.\" 
.\" 
.\" 
.\" 
.SH OPTIONS
.TP 8
.B -v \fRor\fB --version
Prints out FreedroidRPG version information.
.TP 8
.B -q \fRor\fB --nosound
This option will suppress all sound output.  
Very useful if you don't have your sound card configured yet or
don't have any sound hardware at all.
.TP 8
.B -f \fRor\fB --fullscreen
This instructs FreedroidRPG to work in full screen mode, which is the default mode of operation.  
Please note that it is strongly recommended that your X Window system is configured to feature
a move with 640x480 screen resolution, but it will also work if this is not the case.
Note that fullscreen or window mode can also be toggled from within the game via the options
menu.
.TP 8
.B -o \fRor\fB --open_gl
This instructs FreedroidRPG to use OpenGL as the method for graphics output.  If you have
hardware accelerated OpenGL on your X11 or your Microsoft Windows installation, this is the
recommended output method to achieve much better frame rates and also better graphics quality.

NOTE:  If you wish to use OpenGL for graphics output, your FreedroidRPG executable must have
been compiled to support OpenGL.  You can see if that is the case and also if OpenGL graphics
output is active in the very first startup menu of the game.
.TP 8
.B -n \fRor\fB --no_open_gl
This instructs FreedroidRPG to use plain SDL instead of OpenGL as the method for graphics output.
This is usually (much) slower than hardware-accelerated OpenGL graphics output and also some
features are disabled in this mode because of speed considerations.
.TP 8
.B -w \fRor\fB --window
Start FreedroidRPG in a window rather than using full screen mode.
.TP 8
.B -j \fRor\fB --sensitivity
This option can be used to control joystick sensitivity.
.TP 8
.B -d LEVEL \fRor\fB --debug=LEVEL
This option can be used to control debug output of the game.  Debug output will be printed to
stderr, i.e. in most cases to the console you started FreedroidRPG from.  The variable LEVEL
controls how much debug output you would like to have.  LEVEL 0 is the default and means (almost)
no debug output.  LEVEL 1 prints the most important debug messages and LEVEL 2 or LEVEL 3 print
(almost) all debug output, which might be quite a lot.
.\" 
.\" 
.\" 
.\" 
.\" 
.SH HOW TO PLAY
.\" 
.\" 
.B Movement and attacking
.RS
Moving the Tux can now be done exclusively by using the left mouse button.  
Attacking an enemy is done by clicking on that enemy.  
The Tux will, in case of a melee weapon wielded, approach the target and then strike.  
In order to attack an object without moving, you must hold down the shift key and then click the left mouse button.

RUNNING:  If you hold down the left ctrl key, Tux will run instead of walk.

.RE
.\" 
.\" 
.B Talking to people and friendly droids
.RS
When left-clicking the mouse on a friendly character or droid, the Tux will start dialog with that character.
In some cases it might also be that some other person approaches the Tux and opens dialog.
.RE
.\" 
.\" 
.B Reorganizing inventory
.RS
Open up the inventory screen by pressing the 'I' key.
You can now left-click on stuff in your inventory.
That will make you 'hold' the object in question, i.e. your mouse cursor will change into that one item you picked.
If that item can be equipped, you can then equip the item by placing it over the appropriate slot and then left-licking again.
When done with reorganizing inventory, you can press the 'I' key to close inventory screen again.
.RE
.\" 
.\" 
.B Activating a skill or spell
.RS
The Tux in the course of his travels, will learn a lot of skills and spells.  
Some of those will even be present at the very beginning of the game.
In order to use one of the skills of the Tux, this skill must first be selected.
So select a skill, open the skills screen via the 'S' key.
Select the skill of your choice by left clicking onto it.
You can now close the skill screen again by pressing the 'S' key again.
In order to use the selected skill, just press the right mouse button.
Some skills might require some targeting.  
Others will just work on the area where the Tux is standing.
NOTE:  You can also use F1-F10 keys to quick-select a skill.  Fn will
select the n-th present skill, which might be subject to change once
new skills are aquired.
.RE
.\" 
.\" 
.B Opening chests and searching dead bodies or containers
.RS

NEW METHOD:  Clicking the left mouse button on a chest (while standing sufficiently close by) should spill all
the chests content onto the floor.  However there is also the old method of chest interaction, which also allows
you to put stuff back into the chest and take stuff more selectively out of the chest:

OLD METHOD:  To do this, you must be standing in front of the chest or on the dead body and then use the loot skill (see above).  
This skill is easily recognized by the open chest icon used for it.
This will open up an interface screen where you can then trade stuff from your inventory to the container and vice versa.

.RE
.\" 
.\" 
.B Skills and attribute stats of the Tux
.RS
To get an overview of your Tux character, press the 'C' key to open character screen.

You will see the current Strength, Dexterity and Magic stats.  
These will stay very much constant unless you spend some training points with a teacher to raise those attributes.
They are a prerequisite for equipping certain items but also influence the damage the Tux does and also his chance to hit and the like.
Some items might also give you a bonus to your current strength, dexterity or magic scale.
Because of this, there is the 'base' value for the bare Tux and also the 'now' value with all bonuses currently applying.

Apart from this, you can see the most important combat and magic skills of the Tux below.
The range goes novice--average--experienced--skilled--adept--masterful and so on...
These skills strongly influence the speed at which the Tux will strike, the damage he does, the amount of capsules he will have at this disposal in takeover game (see below) and also the amount of force points the Tux can have at most.
To raise these skills, some training points have to be spent with an appropriate teacher for this skill.
.RE
.\" 
.\" 
.B Hacking droids
.RS
The Tux is gifted with a unique inert skill to hack droids.  
He can use this skill on any droid in the game.
In order to hack a bot, which will result in the machine being destroyed, you must first activate the takeover skill.
Then hold down right mouse button to stay in takeover mode.
The next machine touched by the Tux while in this state will be target of the Tux' hacking attempt.
But for this attempt to succeed, the takeover subgame must be won first.
Losing the takeover game will result in the droid being free again and the Tux very much weakened from the failed attempt.
.RE
.\" 
.\" 
.B Playing the takeover subgame
.RS
After the takeover subgame was initiated, the two droids struggling for control will be presented.  
Then the player gets to decide which side of the takeover game he wants to play.  
The player on the left side takes the yellow color, the player on the right side takes the magenta color.  
Note that which side to choose may be the most important decision of the takeover subgame,
cause one side may host strong tactical advantages over the other.  
After sides have been chosen, the takeover capsules will be placed.
Each droid has a limited number of capsules to place and must try to convert the central status bar to his color.
The number of capsules you have at your disposal depends on how much takeover skill you have acquired so far.
Once the takeover subgame is won, the droid in question will be destroyed.
Loss of takeover subgame results in the Tux being very much drained of energy and therefore very vulnerable.
.RE
.\" 
.\" 
.B Keyboard summary
.RS
.TP
.B I
Open/Close Inventory Screen
.TP
.B C
C ... Open/Close Character Screen
.TP
.B S
Open/Close Spells&Skills Screen
.TP
.B L
Show Quest Status Log
.TP
.B P 
Turn on/off Pause Mode
.TP
.B Tab 
Turn on/off automap display
.TP
.B Escape 
Pops up the main menu
.TP
.B F1-F10
Quick-Switch to aquired skill/ability/spells 1-10.  These numbers refer to the list of skills aquired so far and therefore their effect might be subject to some change once the Tux aquires new skills.
.TP
.B 1-9 
Quick-Use items from the quick-inventory.  (That's those small items placed on the very bottom of the inventory.)
.TP
.B Space 
Closes all opened screens.
.TP
.B Left Ctrl Key
Running instead of walking is active as long as you hold down this key.
.TP
.B F12 
Take a screenshot
.RE
.\" 
.\" 
.\" 
.\" 
.\" 
.SH USING THE LEVEL EDITOR
FreedroidRPG comes with a built in level editor.  The level editor can be entered at any point of a running game and it's also possible to continue a game after level editing.  This feature is there for testing and development purposes (and not for cheating).  To enter the level editor, use the 'Level Editor' option from the escape menu inside a running game.

If you wish to make permanent changes to a map and then contribute the map to the Freedroid project, please make sure that you start a fresh game and then edit the fresh map.  Otherwise there will be blood on the floor, items lying around and mission relevant doors already opend and the like.  So best selet 'New Game' and then enter level editor immediately after game startup.

.B How FreedroidRPG maps are organized
.TP
FreedroidRPG maps contain a multitude of data.  The important data types are:
.RS
.TP
.B Floor:
This is for floor tiles like grass floor, grass-and-sand floor, stone floor...  Floor tiles are irrelevant to the Tux movement.
.TP
.B Obstacles:
Obstacles are all the map parts, that are above the floor but still not items that the Tux could pick up, e.g. walls, doors, teleports, chests, ...
.TP
.B Items:
Items are stuff that the Tux can pick up, e.g. laser sword, buckler,...
.TP
.B Level parameters:
Level parameters are values that control the overall properties of the level, like light strength, level size, where the level is connected to other levels, what music tracks to play, ...
.RE

.B Level editor controls
.RS
.TP
.B Moving around:
You can always use the left mouse button to move around on the given map as well as use the cursor keys for this.  To change the current level, you can either use the 'go level north/east/west/south' buttons (if available) or you can press escape to enter the menu and change the level inside the menu.
.TP
.B Floor edit mode:
The FreedroidRPG level editor has 2 modes of operation:  The first mode is floor edit mode.  In floor edit mode, right mouse button will plant floor tiles.  You can use the left mouse button to select the floor tile type from the selection bar. To change from floor edit mode to obstacle edit mode and back again you can use the 'f' key on the keyboard.
.TP
.B Obstacle edit mode:
The other mode is obstacle edit mode.  In obstacle edit mode, right mouse button will plant new obstacles.  You can select the type of obstacle to be planed by clicking the left mouse button into the obstacle selection bar on top of the screen.  However, planing obstacles with the mouse is a bit unprecise.  To plant obstacles in a more precise way, you can use the number pad.  Each of the number pad keys 1-9 will plant the currently marked obstacle to a specific standard location within the tile you're currently standing on.  It doesn't matter where inside this tile you're standing if you use this mode of operation.

In obstacle edit mode, there are also several other keys, that might help to speed up level edit operations.
The 1-8 keys on the normal keyboard (not the number pad!) will select specific wall types.
The T key will select teleporter. 
The R key will select refresh.
The U key will select a chest.
The A key will select an alert.

In obstacle edit mode, you will also notice that if you get close to some obstacle, the obstacle may get 'highlighted' i.e. it's color map will be awkwardly but noticeable shifted.  That means that this obstacle is currently marked.  If you press the 'x' key now, the obstacle in question will be deleted.  
Sometimes there are more than one obstacle associated with the current map square.  If that is so, you can use the 'n' key to switch the marker from one obstacle to the other and back again.
.TP
.B Planting waypoints:
Currently, droids (and that means all non-player characters) move about on a level using predefined waypoints.  To plant a waypoint, press the 'w' key.  This should turn on/off the waypoint on the square where you're standing.
.TP
.B Connecting waypoints:
Waypoints are of no use as long as they are not connected among each other.  To connect one waypoint to another waypoint, go to the first waypoint, press the 'c' key, then go to the second waypoint and press the 'c' key again.  This has established a one-way connection from the first waypoint to the second waypoint.  To allow the droids to move the other way around as well, do the same thing with reversed order of waypoints.  
To inspect the possible ways for droids from one waypoint to other waypoints, just step on the square with the waypoint.  You will notice a dotted line leading from this waypoint to all other waypoints that are possible targets from here.
.TP
.B Planting map labels:
Map labels are not the same as obstacle labels.  Map labels can be used for various purposes, like e.g. to define the point where a teleporter should put the Tux or to define a spot that will cause some event to happen as soon as the Tux steps on this spot.
To define a new map label, press the 'm' key on the keyboard.  You will be prompted for the map label.  Giving an empty string here will delete the existing label on this square.  Note that there will be a colorful circle appearing on any map tile that has been fitted with a map label.
.TP
.B Planting obstacle labels:
Obstacle labels are important so that some obstacles can be marked for events to happen.  If e.g. an event is supposed to remove a special wall obstacle, then this obstacle must be given a name first, so it can be referred to later in the definition of the event.
To plant a label on an obstacle, you must first mark this obstacle (see obstacle mode explanation above).  As soon as the obstacle in question is marked, you can use the 'h' key on the keyboard.  You will be prompted for the new label to attach to this obstacle.  Giving an empty string here will delete any existing obstacle label of this obstacle.
.\" 
.\" 
.\" 
.\" 
.\" 
.SH PROJECT HOME PAGE AND LATEST VERSIONS
The FreedroidRPG project features a home page at freedroid.sourceforge.net.  The project itself is hosted at the Sourceforge.  The project summary page at http://sourceforge.net/projects/freedroid/ can be used to access download and status information.  Note that home page and project summary page are shared with the Freedroid classic development branch as well.
.\" 
.\" 
.\" 
.\" 
.\" 
.SH FILES
.I ~/.freedroid_rpg/config
.RS
The file containing all configuration setting of this user.
.RE
.I ~/.freedroid_rpg/
.RS
Saved games for this user will also be placed in this directory.
.RE
.\" 
.\" 
.\" 
.\" 
.\" 
.SH ENVIRONMENT
FreedroidRPG does currently not care about any environment variables.
.\" 
.\" 
.\" 
.\" 
.\" 
.SH DIAGNOSTICS
Debug output can be produced by using the -d or --debug command line options as described above.
.\" 
.\" 
.\" 
.\" 
.\" 
.SH BUGS, LIMITATIONS AND HELP
While the FreedroidRPG engine can now be considered fairly stable, the story and characters are still far from completed and also the maps are seriously underdeveloped.  If you encounter any problems or bugs, have some idea for future FreedroidRPG development or wish to contribute in some way, please send e-mail to <freedroid-discussion@lists.sourceforge.net>.  
.\" 
.\" 
.\" 
.\" 
.\" 
.SH AUTHOR
Johannes Prix, 
Reinhard Prix,
Bastian Salmela.
.\" 
.\" 
.\" 
.\" 
.\" 
.SH "SEE ALSO"
.BR freedroid (6),
