.\" Process this file with
.\" groff -man -Tascii freedroidRPG.6
.\" 
.\" Or even better, use
.\" 
.\"    man -l freedroidRPG.6 
.\" 
.\" to test the local copy of the man page source file.
.\" 
.TH FREEDROID 6 "MARCH 2003" Linux "User Manuals"
.SH NAME
freedroidRPG \- a graphical single player role playing game featuring Tux the Linux mascot
.\" 
.\" 
.\" 
.\" 
.\" 
.SH SYNOPSIS
.B freedroidRPG [ options
.B ]
.SH DESCRIPTION
.B FreedroidRPG
is a graphical single player role playing game inspired by games like Diablo and Gothic.

In a far-future world, almost all services and jobs were done by robots and droids,
most especially the more dangerous ones like police or military services.
The company providing the operating systems for these bots 'MegaSoft' used their
closed source operating system monopoly and a back door within it's operation system
to enslave humanity all over the galaxy.

But this is not the main problem.  Some 20 years after the MS has taken control of the 
universe, suddenly a very strange thing happened.  The bots suddenly rebelled against 
the MS and didn't respond to the commands of their former superiors at the MS any more.
Mankind was under attack by it's bots and had to flee to various secret underground
caverns on remote planets of the universe and cannot return any more.

This is where the game begins.  The Tux awakens from 200000 years of stasis to save
the world.
.\" 
.\" 
.\" 
.\" 
.\" 
.SH OPTIONS
.TP 8
.B -v \fRor\fB --version
Prints out FreedroidRPG version information.
.TP 8
.B -q \fRor\fB --nosound
This option will suppress all sound output.  
Very useful if you don't have your sound card configured yet or
don't have any sound hardware at all.
.TP 8
.B -f \fRor\fB --fullscreen
This instructs FreedroidRPG to work in full screen mode, which is the default mode of operation.  
Please note that it is strongly recommended that your X Window system is configured to feature
a move with 640x480 screen resolution, but it will also work if this is not the case.
Note that fullscreen or window mode can also be toggled from within the game via the options
menu.
.TP 8
.B -w \fRor\fB --window
Start FreedroidRPG in a window rather than using full screen mode.
.TP 8
.B -j \fRor\fB --sensitivity
This option can be used to control joystick sensitivity.
.TP 8
.B -d LEVEL \fRor\fB --debug=LEVEL
This option can be used to control debug output of the game.  Debug output will be printed to
stderr, i.e. in most cases to the console you started FreedroidRPG from.  The variable LEVEL
controls how much debug output you would like to have.  LEVEL 0 is the default and means (almost)
no debug output.  LEVEL 1 prints the most important debug messages and LEVEL 2 or LEVEL 3 print
(almost) all debug output, which might be quite a lot.
.\" 
.\" 
.\" 
.\" 
.\" 
.SH HOW TO PLAY
.\" 
.\" 
.B Movement and attacking
.RS
Moving the Tux can now be done exclusively by using the left mouse button.  
Attacking an enemy is done by clicking on that enemy.  
The Tux will, in case of a melee weapon wielded, approach the target and then strike.  
In order to attack an object without moving, you must hold down the shift key and then click the left mouse button.
.RE
.\" 
.\" 
.B Talking to people and friendly droids
.RS
When left-clicking the mouse on a friendly character or droid, the Tux will start dialog with that character.
In some cases it might also be that some other person approaches the Tux and opens dialog.
.RE
.\" 
.\" 
.B Reorganizing inventory
.RS
Open up the inventory screen by pressing the 'I' key.
You can now left-click on stuff in your inventory.
That will make you 'hold' the object in question, i.e. your mouse cursor will change into that one item you picked.
If that item can be equipped, you can then equip the item by placing it over the appropriate slot and then left-licking again.
When done with reorganizing inventory, you can press the 'I' key to close inventory screen again.
.RE
.\" 
.\" 
.B Activating a skill or spell
.RS
The Tux in the course of his travels, will learn a lot of skills and spells.  
Some of those will even be present at the very beginning of the game.
In order to use one of the skills of the Tux, this skill must first be selected.
So select a skill, open the skills screen via the 'S' key.
Select the skill of your choice by left clicking onto it.
You can now close the skill screen again by pressing the 'S' key again.
In order to use the selected skill, just press the right mouse button.
Some skills might require some targeting.  
Others will just work on the area where the Tux is standing.
.RE
.\" 
.\" 
.B Opening chests and searching dead bodies or containers
.RS
To do this, you must be standing in front of the chest or on the dead body and then use the loot skill (see above).  
This skill is easily recognized by the open chest icon used for it.
This will open up an interface screen where you can then trade stuff from your inventory to the container and vice versa.
.RE
.\" 
.\" 
.B Skills and attribute stats of the Tux
.RS
To get an overview of your Tux character, press the 'C' key to open character screen.

You will see the current Strength, Dexterity and Magic stats.  
These will stay very much constant unless you spend some training points with a teacher to raise those attributes.
They are a prerequisite for equipping certain items but also influence the damage the Tux does and also his chance to hit and the like.
Some items might also give you a bonus to your current strength, dexterity or magic scale.
Because of this, there is the 'base' value for the bare Tux and also the 'now' value with all bonuses currently applying.

Apart from this, you can see the most important combat and magic skills of the Tux below.
The range goes novice--average--experienced--skilled--adept--masterful and so on...
These skills strongly influence the speed at which the Tux will strike, the damage he does, the amount of capsules he will have at this disposal in takeover game (see below) and also the amount of force points the Tux can have at most.
To raise these skills, some training points have to be spent with an appropriate teacher for this skill.
.RE
.\" 
.\" 
.B Hacking droids
.RS
The Tux is gifted with a unique inert skill to hack droids.  
He can use this skill on any droid in the game.
In order to hack a bot, which will result in the machine being destroyed, you must first activate the takeover skill.
Then hold down right mouse button to stay in takeover mode.
The next machine touched by the Tux while in this state will be target of the Tux' hacking attempt.
But for this attempt to succeed, the takeover subgame must be won first.
Losing the takeover game will result in the droid being free again and the Tux very much weakened from the failed attempt.
.RE
.\" 
.\" 
.RE
.B Playing the takeover subgame
.RS
After the takeover subgame was initiated, the two droids struggling for control will be presented.  
Then the player gets to decide which side of the takeover game he wants to play.  
The player on the left side takes the yellow color, the player on the right side takes the magenta color.  
Note that which side to choose may be the most important decision of the takeover subgame,
cause one side may host strong tactical advantages over the other.  
After sides have been chosen, the takeover capsules will be placed.
Each droid has a limited number of capsules to place and must try to convert the central status bar to his color.
The number of capsules you have at your disposal depends on how much takeover skill you have acquired so far.
Once the takeover subgame is won, the droid in question will be destroyed.
Loss of takeover subgame results in the Tux being very much drained of energy and therefore very vulnerable.
.RE
.\" 
.\" 
.\" 
.\" 
.\" 
.SH PROJECT HOME PAGE AND LATEST VERSIONS
The FreedroidRPG project features a home page at freedroid.sourceforge.net.  The project itself is hosted at the Sourceforge.  The project summary page at http://sourceforge.net/projects/freedroid/ can be used to access download and status information.  Note that home page and project summary page are shared with the Freedroid classic development branch as well.
.\" 
.\" 
.\" 
.\" 
.\" 
.SH FILES
.I ~/.freedroid_rpg/config
.RS
The file containing all configuration setting of this user.
.RE
.I ~/.freedroid_rpg/
.RS
Saved games for this user will also be placed in this directory.
.RE
.\" 
.\" 
.\" 
.\" 
.\" 
.SH ENVIRONMENT
FreedroidRPG does currently not care about any environment variables.
.\" 
.\" 
.\" 
.\" 
.\" 
.SH DIAGNOSTICS
Debug output can be produced by using the -d or --debug command line options as described above.
.\" 
.\" 
.\" 
.\" 
.\" 
.SH BUGS, LIMITATIONS AND HELP
While the FreedroidRPG engine can now be considered fairly stable, the story and characters are still far from completed and also the maps are seriously underdeveloped.  If you encounter any problems or bugs, have some idea for future FreedroidRPG development or wish to contribute in some way, please send e-mail to <freedroid-discussion@lists.sourceforge.net>.  
.\" 
.\" 
.\" 
.\" 
.\" 
.SH AUTHOR
Johannes Prix, 
Reinhard Prix,
Bastian Salmela, 
Lanzz.
.\" 
.\" 
.\" 
.\" 
.\" 
.SH "SEE ALSO"
.BR freedroid (6),
